# Site settings
title: Jazmin Collins Personal Website
description: Jazmin Collins
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jazmin Collins
user_description: Work-a-holic computer science student with 9+ years of participation in various technology programs, competitions, conferences, and challenges. Specialties in data analysis with SQL and GCP, machine learning through Python and GCP, and virtual reality with Unity and C#. Best progamming languages are Java, Python, and SQL, with basic experience in C# and HTML/CSS.
user_title: Data Science Enthusiast
email: collinsjazmin.21@gmail.com
twitter_username: lorem_ipsum
github_username:  https://github.com/jcollins-01

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
