# Site settings
title: Jazmin Collins Personal Website
description: Jazmin Collins
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jazmin Collins
user_description: Work-a-holic college student.
user_title: Data Science Nerd
email: collinsjazmin.21@gmail.com
twitter_username: lorem_ipsum
github_username:  https://github.com/jcollins-01

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
